quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/catalogo
quarkus.hibernate-orm.database.generation=update
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n
database.generation=update

# Swagger/OpenAPI Configuration
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger-ui
# API Information
mp.openapi.scan.disable=false
quarkus.smallrye-openapi.info-title=Tea and Snacks API 
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API for managing teas and snacks
quarkus.smallrye-openapi.info-contact-email=sys.yugulis@gmail.com
quarkus.smallrye-openapi.info-contact-name=Tea and Snacks Support
