quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/catalogo
quarkus.hibernate-orm.database.generation=update
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n
database.generation=update